"#version 450 core\n"
"\n"
"// Uniforms to control copy process\n"
"layout (location = 0) uniform int red;\n"
"layout (location = 1) uniform int green;\n"
"layout (location = 2) uniform int blue;\n"
"\n"
"// Output value\n"
"out uvec4 colour;\n"
"\n"
"// Set rectangle pixel to right colour\n"
"void main(void) {\n"
"	colour = uvec4((red >> 3) & 0x1F, (green >> 3) & 0x1F, (blue >> 3) & 0x1F, 0);\n"
"}\n"
